java_import(
    name = "wpimath",
    jars = ["@__bazelrio_edu_wpi_first_wpimath_wpimath-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/wpimath:jni",
        "//libraries/java/wpilib/wpiutil",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_annotations",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_core",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
