cc_library(
    name = "netcomm",
    srcs = [
        "@__bazelrio_edu_wpi_first_ni-libraries_netcomm_linuxathena//:shared_libs",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
