java_import(
    name = "wpiutil",
    jars = ["@__bazelrio_edu_wpi_first_wpiutil_wpiutil-java//jar:file"],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/cpp/wpilib/wpiutil:jni",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_annotations",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_core",
        "@__bazelrio_maven_deps//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
